### ISSUE TITLE
Implement `NewTransactionRequest`

### ISSUE THREAD

**Issue by jules** [dusk-network/rusk-schema#13]
It is referenced in `bid.proto`, but still missing.
```
bid.proto:27:5: "rusk.NewTransactionRequest" is not defined.
```

**Comment by CPerezz** [comment]
Yep that's right. 

I'll add the rpc method!

**Comment by CPerezz** [comment]
Hmm

Now that I'm looking a bit deeper into this. Looks to me that what we should add here is a `Transaction`.  Makes sense @julesdesmit ?

**Comment by CPerezz** [comment]
Closing this since it's already implemented.
